General/urls.py
from django.urls import path
from .views import *

app_name = 'general'
urlpatterns = [
    path('', LoginForm, name='login'),
    path('profile/logout/', logout, name='logout'),
    path('profile/signup/', signup, name='signup'),
    path('profile/verify/', Verify, name='verify'),
    path('profile/generate-otp/', GenerateOtp, name='generateotp'),
    path('signup/create-profile/', CreateProfile, name='profile'),
    path('profile/change-password/', ChangePassword, name='passwordreset'),
    path('profile/change-avatar/', ChangeAvatar, name='changeavatar'),
    path('profile/edit-profile/', EditProfile, name='editprofile'),
    path('profile/save-image/<str:location>/<str:prof_id>', SaveImage, name='saveimage'),
    path('testurl/', TestUrl, name='testurl'),
    path('post/<str:username>/<str:type>/<str:post_id>/', PostsDetailPage, name='testurl'),
    
    path('notifications/mark-as-read/<str:notifi_id>/<str:userprofile_id>', MarkAsRead, name='markasread'),
    path('notifications/mark-allas-read/<str:userprofile_id>', MarkAllAsRead, name='markallasread'),
    path('change/email-number/', ChangeEmailNumber, name='change_email_number'),
    path('profile/edit-profile/banksettings/', BankSetting, name='banksetting'),
    path('profile/edit-profile/editbanksettings/', BankEditSetting, name='editbanksetting'),
    path('profile/edit-profile/publicProfileSetting/', PublicProfileSetting, name='publicprofilesetting'),
    path('profile/edit-profile/publicProfileSettingDone/', PublicProfileSettingDone, name='publicprofilesettingdone'),
    path('profile/update-shipping-addr/<str:product_id>/<str:creator_profileId>', UpdateShippingAddr, name='updateshippingaddr'),
]

Posts/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('profile/dashboard/create-post/', CreatePostView, name='createpost'),
    path('profile/dashboard/my-post/', MyPostView, name='mypost'),
    path('profile/dashboard/delete-post/', DeletePostView, name='deletepost'),
    path('profile/dashboard/all-video-post/', AllVideosView, name='allvideopost'),
    
    path('profile/dashboard/all-image-post/', AllImagesView, name='allimagepost'),
    path('profile/dashboard/image-post/', ImagePostView, name='imagepost'),
    path('profile/dashboard/video-post/', VideoPostView, name='videopost'),
    path('profile/dashboard/save-post/<str:post_category>', SavePostView, name="save-post"),
    path('profile/dashboard/edit-post/<str:post_category>/<str:Id>/', EditPostView, name="edit-post"),
    path('profile/dashboard/update-post/<str:post_category>/<str:Id>/', UpdatePostView, name="update-post"),
    path('profile/dashboard/delete-post/<str:post_category>/<str:Id>/', DeletePostView, name="delete-post"),
    path('profile/dashboard/publish-post/<str:post_category>/<str:Id>/', PublishPostView, name="publish-post"),
    path('profile/dashboard/unpublish-post/<str:post_category>/<str:Id>/', UnPublishPostView, name="unpublish-post"),
    path('profile/dashboard/published-post/<str:post_category>/', PublishedPostView, name="published-post"),
    path('like/', LikeBtnView,name="likebtn"),
 ]

zocaya_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from General.views import ProfileFilterView, UserProfilePages, Follow, Unfollow, PostsDetailPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls', namespace='posts')),
    path('', include('General.urls', namespace='generals')),
    path('', include('Dashboard.urls', namespace='dashboards')),
    path('', include('Store.urls', namespace='store')),
    path('', include('paymentgateway.urls', namespace='paymentgateway')),
    path('accounts/', include('allauth.urls')),
    path('<str:username>/', ProfileFilterView, name="profile-filter"),
    path('<str:username>/user-profile/<str:type>/', UserProfilePages, name="userprofilepages"),
    path('follow/<str:username>', Follow, name="followpage"),
    path('unfollow/<str:username>', Unfollow, name="unfollowpage"),
    path('post/<str:username>/<str:type>/<str:post_id>', PostsDetailPage, name="postsdetailpage"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

General/views.py
from django.shortcuts import render,redirect
from django.contrib import auth, messages
from .models import *
from Posts.models import *
from Store.models import *
from django.core.files.storage import FileSystemStorage
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from zocaya_new.settings import *
# from Zocaya.settings import *
import json,uuid
from Posts.models import Notification
import time, threading
from django.core.mail import send_mail
import random
from django.core.paginator import Paginator
from django.template import loader
from imagekitio import ImageKit
from media import *

imagekit = ImageKit(
    private_key='private_lLLidL7grmjC6y/uuR98dEGlvPM=',
    public_key='public_2e8JMemRIR9zGN+aIQB3dSRPnK0=',
    url_endpoint='https://ik.imagekit.io/xfu94rzcsoi/'
)


def UpdateShippingAddr(request,product_id,creator_profileId):
    if request.user.is_authenticated:
      shiping_addr=ShippingAddress.objects.filter(User=request.user)
      if request.method=='POST':
        state=request.POST['state']
        pincode=request.POST['pincode']
        city=request.POST['city']
        address=request.POST['address']
        shiping_addr.update(
            address_line=address,
            state=state,
            pin_code=pincode,
            city=city
        )
        customer_profileId=Profile.objects.get(user=request.user).Id.hex
        return redirect("paymentgateway:paymentgateway",creator_profileId,customer_profileId,product_id)
    
    else:
        return redirect("general:login")

def LoginForm(request):
    my_user = request.user
    #If you want to know if the user is logged in
    is_user_logged = my_user.is_authenticated
    if is_user_logged:
        return redirect('dashboard:dashboard')
    if request.method=="POST":
        email=request.POST['uname']
        try:
            uname=User.objects.get(email=email).username
        except:
            return render(request,'General/index.html',{'error':'Invalid Email Address'})
        pwd=request.POST['pass']
        user=auth.authenticate(username=uname,password=pwd)
        if user is not None:
            auth.login(request,user)
            return redirect(request.path)
        else:
            return render(request,'General/index.html',{'error':'Invalid Credentials'})
    return render(request,'General/index.html')

    # return render(request, 'General/login.html', {})


def signup(request, backend='django.contrib.auth.backends.ModelBackend'):
     if request.method=="POST":
          # Create a user
          print("ok1")
     
          if request.POST['pass']==request.POST['passConfirm']:
               print("ok2")
               # Both the passwords have been matched
               # Now check if user exist or not
               try:

                    username = request.POST['username']
                    print("ok2")
                    if " " in username:
                        return render(request,'General/signup.html',{'error':'username cannot have spaces'})
                        
                    user=User.objects.get(username=username)
                    return render(request,'General/signup.html',{'error':'user already exist'})
                    
               except User.DoesNotExist:
                    try:
                        print("ok3")
                        email=request.POST['email']
                        temp=User.objects.get(email=email)
                        return render(request,'General/signup.html',{'error':'Email exist'})
                    except:
                        print("ok4")
                        user=User.objects.create_user(username=request.POST['username'],
                                                    password=request.POST['pass'],
                                                    email=email
                                                    )                                        
                        auth.login(request,user, backend='django.contrib.auth.backends.ModelBackend')
                        print(user)
                        return redirect('general:profile')
          else:
               return render(request,'General/signup.html',{'error':'password does not match'})
                                 
     return render(request,'General/signup.html')

def Verify(request):
    my_user=request.user
    if request.method=="POST":
        otpMail=request.POST['otpmail']
        # otpSms=request.POST['otpsms']
        print(otpMail)
        # print(otpSms)
        profile=Profile.objects.get(user=my_user)
        if int(profile.otp_for_email)==int(otpMail):
            Profile.objects.filter(user=my_user).update(Account_activated=True)
            return redirect('dashboard:dashboard')
        else:
             return render(request,'General/otpEmail.html',{'profile':profile,'message':'Invalid OTP,Please Try Again'})
            
            
    if my_user.is_authenticated:
        profile=Profile.objects.get(user=my_user)
        if not profile.Account_activated:
            return render(request,'General/otpEmail.html',{'profile':profile})
        else:
            return redirect('dashboard:dashboard')
        
@csrf_exempt
def GenerateOtp(request):
    my_user=request.user
    print(my_user)
    profile=Profile.objects.get(user=my_user)
    print(my_user)
    if request.method=='POST' and my_user.is_authenticated and profile.otp_for_email==0 :
        print("ok",my_user)
        received_json_data= json.loads(request.body)
        username=received_json_data['username']    
        thread=threading.Thread(target=create_timeout,args=(username,))
        thread.start()
        account_sid = 'xxxxxxxxxxxxxxxxxxx'
        auth_token = 'xxxxxxxxxxxxxxxxxxxxxxxx'
        # client = Client(account_sid, auth_token)
        # otp_mob=random.randint(111111,999999)
        otp_mail=random.randint(111111,999999)
        Profile.objects.filter(user=my_user).update(otp_for_email=otp_mail)
        # message = client.messages \
        #                 .create(
        #                     body="Your OTP is "+str(otp_mob),
        #                     from_='+xxxxx33',
        #                     to=str(profile.Phone_no)
        #                 )
        send_mail(
        "Verification Mail",
        "Hi Zocaya User\nYour Zocaya OTP is :"+str(otp_mail)+"\n\n You are receiving this OTP because your email has been used to sign up on zocaya.com\n\nIf you have not signed up on zocaya, please contact us on zocayamedia@gmail.com and we will investigate the issue further \n\n Thanks,\nZocaya Team",
        "zocayamedia@gmail.com",
        [str(profile.user.email)],
        fail_silently=True
            )
        print(username)
        return JsonResponse({'success':True})
    else:
        return JsonResponse({'success':False}) 

@login_required(login_url='/')
def ChangeEmailNumber(request):
    my_user=request.user
    if my_user.is_authenticated:
            if request.method=='POST':
                email=request.POST['mail']
                # mob_no=request.POST['number']
                User.objects.filter(username=my_user).update(email=email)
                # Profile.objects.filter(user=my_user).update(Phone_no=mob_no)
                profile=Profile.objects.get(user=my_user)
                return render(request,'General/changeEmailNumber.html',{'profile':profile,'message':'change successfully!'})
            else:
                profile=Profile.objects.get(user=my_user)
                return render(request,'General/changeEmailNumber.html',{'profile':profile})
    else:
            return redirect('general:login')
@login_required(login_url='/')
def logout(request):
    my_user = request.user
        #If you want to know if the user is logged in
    is_user_logged = my_user.is_authenticated
    if is_user_logged:
        auth.logout(request)
    return redirect('general:login')

@login_required(login_url='/')
def CreateProfile(request):
    my_user = request.user

    profile = Profile.objects.filter(Profile_incomplete=False, user=my_user)
    if profile.exists():
        return redirect('dashboard:dashboard')
    else:
        if request.method=="POST":

            if 'dp_input' in request.FILES:
                f=request.FILES
                f = f['dp_input']

                upload = imagekit.upload(
                    file=open(f.temporary_file_path(), "rb"),
                    file_name="image-post/" + str(my_user.email) + "/" + str(f),
                    options={
                        "response_fields": ["is_private_file", "tags"],

                    },
                )
                src = upload['response']['url']
                fileid=upload['response']['fileId']
            else:
                upload = imagekit.upload(
                    file=open('./media/avatar.jpg', "rb"),
                    file_name="image-post/" + str(my_user.email) + "/" +'dp',
                    options={
                        "response_fields": ["is_private_file", "tags"],

                    },
                )
                src = upload['response']['url']
                fileid = upload['response']['fileId']

            profile=Profile.objects.create(
                Name= request.POST['username'],
                username= my_user.username,
                Gender = request.POST['gender'],
                UserType=request.POST['usertype'],
                user = my_user,
                Avatar=src,
                fileid=fileid,
                DateOfBirth = request.POST['dob'],
                URL="/"+str(my_user),
                tab_order='image,videos,articles',
                Country = request.POST['country'],
                
                Phone_no = request.POST['num'],
                Bio = request.POST['aboutme'],
                Profile_incomplete=False,
            )

General/templates/checkout_addrForm.html
{% if visitor_profile %}

<form method="POST" id="form{{forloop.counter}}" action="{% url 'general:updateshippingaddr' post.Id.hex profile.Id.hex %}">
    {% csrf_token %}
    <div class="form-group">
        <label class="form-label" for="exampleInputEmail1">Email(Not Editable)</label>
        <input disabled required type="text" name="AccNum" value="{{visitor_profile.user.email}}" class="mb-3 disabled form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">

    </div>
    <div class="form-group">
        <label class="form-label" for="exampleInputEmail1">Your Name(Not Editable)</label>
        <input required type="text" name="code" value="{{visitor_profile.Name}}" disabled class="mb-3 form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">

    </div>
    <div class="form-group">
        <label class="form-label" for="exampleInputEmail1">Phone Number</label>
        <input required type="text" name="AccName" value="{{visitor_profile.Phone_no}}" class="mb-3 form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">

    </div>
    <label class="form-label" for="address">Address</label>
    <div class="row" id="address">
        <div class="col">
            <input required type="text" id="addrLine{{forloop.counter}}" name="address" value="{{addr.address_line}}" class="form-control  form-control-sm " placeholder="Delivery Address">
        </div>
        <div class="col">
            <input required type="text" id="city{{forloop.counter}}" name="city" value="{{addr.city}}" class="form-control  form-control-sm" placeholder="City">
        </div>
    </div>
    <div class="row mt-3">
        <div class="col">
            <input required type="text" id="state{{forloop.counter}}" name="state" value="{{addr.state}}" class="form-control  form-control-sm " placeholder="State">
        </div>
        <div class="col">
            <input required type="tel" id="pincode{{forloop.counter}}" name="pincode" value="{{addr.pin_code}}" class="form-control  form-control-sm" placeholder="Pincode">
        </div>
    </div>

    <button type="submit" id="submitAddr" style="display: none;" class="btn btn-success btn-sm mt-4">Next</button>
</form>
{% else %}
<h1>Login First To Make Purchase</h1>
{% endif %}

General/templates/countries.html
<div class="input-group my-2">

    <label class="input-group-text" for="countries">Your Countries</label>


    <select class="form-select" name="country" value="{{profile.Country}}" id="countries">
        {% if profile.Country %}
        <option>{{profile.Country}}</option>
        {% else %}
        <option>Select Country</option>
        {% endif %}
        <option value="AF">Afghanistan</option>
        <option value="AX">Aland Islands</option>
        <option value="AL">Albania</option>
        <option value="DZ">Algeria</option>
        <option value="AS">American Samoa</option>
        <option value="AD">Andorra</option>
        <option value="AO">Angola</option>
        <option value="AI">Anguilla</option>
        <option value="AQ">Antarctica</option>
        <option value="AG">Antigua and Barbuda</option>
        <option value="AR">Argentina</option>
        <option value="AM">Armenia</option>
        <option value="AW">Aruba</option>
        <option value="AU">Australia</option>
        <option value="AT">Austria</option>
        <option value="AZ">Azerbaijan</option>
        <option value="BS">Bahamas</option>
        <option value="BH">Bahrain</option>
        <option value="BD">Bangladesh</option>
        <option value="BB">Barbados</option>
        <option value="BY">Belarus</option>
        <option value="BE">Belgium</option>
        <option value="BZ">Belize</option>
        <option value="BJ">Benin</option>
        <option value="BM">Bermuda</option>
        <option value="BT">Bhutan</option>
        <option value="BO">Bolivia</option>
        <option value="BQ">Bonaire, Sint Eustatius and Saba</option>
        <option value="BA">Bosnia and Herzegovina</option>
        <option value="BW">Botswana</option>
        <option value="BV">Bouvet Island</option>
        <option value="BR">Brazil</option>
        <option value="IO">British Indian Ocean Territory</option>
        <option value="BN">Brunei Darussalam</option>
        <option value="BG">Bulgaria</option>
        <option value="BF">Burkina Faso</option>
        <option value="BI">Burundi</option>
        <option value="KH">Cambodia</option>
        <option value="CM">Cameroon</option>
        <option value="CA">Canada</option>
        <option value="CV">Cape Verde</option>
        <option value="KY">Cayman Islands</option>
        <option value="CF">Central African Republic</option>
        <option value="TD">Chad</option>
        <option value="CL">Chile</option>
        <option value="CN">China</option>
        <option value="CX">Christmas Island</option>
        <option value="CC">Cocos (Keeling) Islands</option>
        <option value="CO">Colombia</option>
        <option value="KM">Comoros</option>
        <option value="CG">Congo</option>
        <option value="CD">Congo, the Democratic Republic of the</option>
        <option value="CK">Cook Islands</option>
        <option value="CR">Costa Rica</option>
        <option value="CI">Cote D'Ivoire</option>
        <option value="HR">Croatia</option>
        <option value="CU">Cuba</option>
        <option value="CW">Curacao</option>
        <option value="CY">Cyprus</option>
        <option value="CZ">Czech Republic</option>
        <option value="DK">Denmark</option>
        <option value="DJ">Djibouti</option>
        <option value="DM">Dominica</option>
        <option value="DO">Dominican Republic</option>
        <option value="EC">Ecuador</option>
        <option value="EG">Egypt</option>
        <option value="SV">El Salvador</option>
        <option value="GQ">Equatorial Guinea</option>
        <option value="ER">Eritrea</option>
        <option value="EE">Estonia</option>
        <option value="ET">Ethiopia</option>
        <option value="FK">Falkland Islands (Malvinas)</option>
        <option value="FO">Faroe Islands</option>
        <option value="FJ">Fiji</option>
        <option value="FI">Finland</option>
        <option value="FR">France</option>
        <option value="GF">French Guiana</option>
        <option value="PF">French Polynesia</option>
        <option value="TF">French Southern Territories</option>
        <option value="GA">Gabon</option>
        <option value="GM">Gambia</option>
        <option value="GE">Georgia</option>
        <option value="DE">Germany</option>
        <option value="GH">Ghana</option>
        <option value="GI">Gibraltar</option>
        <option value="GR">Greece</option>
        <option value="GL">Greenland</option>
        <option value="GD">Grenada</option>
        <option value="GP">Guadeloupe</option>
        <option value="GU">Guam</option>
        <option value="GT">Guatemala</option>
        <option value="GG">Guernsey</option>
        <option value="GN">Guinea</option>
        <option value="GW">Guinea-Bissau</option>
        <option value="GY">Guyana</option>
        <option value="HT">Haiti</option>
        <option value="HM">Heard Island and Mcdonald Islands</option>
        <option value="VA">Holy See (Vatican City State)</option>
        <option value="HN">Honduras</option>
        <option value="HK">Hong Kong</option>
        <option value="HU">Hungary</option>
        <option value="IS">Iceland</option>
        <option value="IN">India</option>
        <option value="ID">Indonesia</option>
        <option value="IR">Iran, Islamic Republic of</option>
        <option value="IQ">Iraq</option>
        <option value="IE">Ireland</option>
        <option value="IM">Isle of Man</option>
        <option value="IL">Israel</option>
        <option value="IT">Italy</option>
        <option value="JM">Jamaica</option>
        <option value="JP">Japan</option>
        <option value="JE">Jersey</option>
        <option value="JO">Jordan</option>
        <option value="KZ">Kazakhstan</option>
        <option value="KE">Kenya</option>
        <option value="KI">Kiribati</option>
        <option value="KP">Korea, Democratic People"s Republic of</option>
        <option value="KR">Korea, Republic of</option>
        <option value="XK">Kosovo</option>
        <option value="KW">Kuwait</option>
        <option value="KG">Kyrgyzstan</option>
        <option value="LA">Lao People's Democratic Republic</option>
        <option value="LV">Latvia</option>
        <option value="LB">Lebanon</option>
        <option value="LS">Lesotho</option>
        <option value="LR">Liberia</option>
        <option value="LY">Libyan Arab Jamahiriya</option>
        <option value="LI">Liechtenstein</option>
        <option value="LT">Lithuania</option>
        <option value="LU">Luxembourg</option>
        <option value="MO">Macao</option>
        <option value="MK">Macedonia, the Former Yugoslav Republic of</option>
        <option value="MG">Madagascar</option>
        <option value="MW">Malawi</option>
        <option value="MY">Malaysia</option>
        <option value="MV">Maldives</option>
        <option value="ML">Mali</option>
        <option value="MT">Malta</option>
        <option value="MH">Marshall Islands</option>
        <option value="MQ">Martinique</option>
        <option value="MR">Mauritania</option>
        <option value="MU">Mauritius</option>
        <option value="YT">Mayotte</option>
        <option value="MX">Mexico</option>
        <option value="FM">Micronesia, Federated States of</option>
        <option value="MD">Moldova, Republic of</option>
        <option value="MC">Monaco</option>
        <option value="MN">Mongolia</option>
        <option value="ME">Montenegro</option>
        <option value="MS">Montserrat</option>
        <option value="MA">Morocco</option>
        <option value="MZ">Mozambique</option>
        <option value="MM">Myanmar</option>
        <option value="NA">Namibia</option>
        <option value="NR">Nauru</option>
        <option value="NP">Nepal</option>
        <option value="NL">Netherlands</option>
        <option value="AN">Netherlands Antilles</option>
        <option value="NC">New Caledonia</option>
        <option value="NZ">New Zealand</option>
        <option value="NI">Nicaragua</option>
        <option value="NE">Niger</option>
        <option value="NG">Nigeria</option>
        <option value="NU">Niue</option>
        <option value="NF">Norfolk Island</option>
        <option value="MP">Northern Mariana Islands</option>
        <option value="NO">Norway</option>
        <option value="OM">Oman</option>
        <option value="PK">Pakistan</option>
        <option value="PW">Palau</option>
        <option value="PS">Palestinian Territory, Occupied</option>
        <option value="PA">Panama</option>
        <option value="PG">Papua New Guinea</option>
        <option value="PY">Paraguay</option>
        <option value="PE">Peru</option>
        <option value="PH">Philippines</option>
        <option value="PN">Pitcairn</option>
        <option value="PL">Poland</option>
        <option value="PT">Portugal</option>
        <option value="PR">Puerto Rico</option>
        <option value="QA">Qatar</option>
        <option value="RE">Reunion</option>
        <option value="RO">Romania</option>
        <option value="RU">Russian Federation</option>
        <option value="RW">Rwanda</option>
        <option value="BL">Saint Barthelemy</option>
        <option value="SH">Saint Helena</option>
        <option value="KN">Saint Kitts and Nevis</option>
        <option value="LC">Saint Lucia</option>
        <option value="MF">Saint Martin</option>
        <option value="PM">Saint Pierre and Miquelon</option>
        <option value="VC">Saint Vincent and the Grenadines</option>
        <option value="WS">Samoa</option>
        <option value="SM">San Marino</option>
        <option value="ST">Sao Tome and Principe</option>
        <option value="SA">Saudi Arabia</option>
        <option value="SN">Senegal</option>
        <option value="RS">Serbia</option>
        <option value="CS">Serbia and Montenegro</option>
        <option value="SC">Seychelles</option>
        <option value="SL">Sierra Leone</option>
        <option value="SG">Singapore</option>
        <option value="SX">Sint Maarten</option>
        <option value="SK">Slovakia</option>
        <option value="SI">Slovenia</option>
        <option value="SB">Solomon Islands</option>
        <option value="SO">Somalia</option>
        <option value="ZA">South Africa</option>
        <option value="GS">South Georgia and the South Sandwich Islands</option>
        <option value="SS">South Sudan</option>
        <option value="ES">Spain</option>
        <option value="LK">Sri Lanka</option>
        <option value="SD">Sudan</option>
        <option value="SR">Suriname</option>
        <option value="SJ">Svalbard and Jan Mayen</option>
        <option value="SZ">Swaziland</option>
        <option value="SE">Sweden</option>
        <option value="CH">Switzerland</option>
        <option value="SY">Syrian Arab Republic</option>
        <option value="TW">Taiwan, Province of China</option>
        <option value="TJ">Tajikistan</option>
        <option value="TZ">Tanzania, United Republic of</option>
        <option value="TH">Thailand</option>
        <option value="TL">Timor-Leste</option>
        <option value="TG">Togo</option>
        <option value="TK">Tokelau</option>
        <option value="TO">Tonga</option>
        <option value="TT">Trinidad and Tobago</option>
        <option value="TN">Tunisia</option>
        <option value="TR">Turkey</option>
        <option value="TM">Turkmenistan</option>
        <option value="TC">Turks and Caicos Islands</option>
        <option value="TV">Tuvalu</option>
        <option value="UG">Uganda</option>
        <option value="UA">Ukraine</option>
        <option value="AE">United Arab Emirates</option>
        <option value="GB">United Kingdom</option>
        <option value="US">United States</option>
        <option value="UM">United States Minor Outlying Islands</option>
        <option value="UY">Uruguay</option>
        <option value="UZ">Uzbekistan</option>
        <option value="VU">Vanuatu</option>
        <option value="VE">Venezuela</option>
        <option value="VN">Viet Nam</option>
        <option value="VG">Virgin Islands, British</option>
        <option value="VI">Virgin Islands, U.s.</option>
        <option value="WF">Wallis and Futuna</option>
        <option value="EH">Western Sahara</option>
        <option value="YE">Yemen</option>
        <option value="ZM">Zambia</option>
        <option value="ZW">Zimbabwe</option>
        
    </select>

</div>