Posts/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('profile/dashboard/create-post/', CreatePostView, name='createpost'),
    path('profile/dashboard/my-post/', MyPostView, name='mypost'),
    path('profile/dashboard/delete-post/', DeletePostView, name='deletepost'),
    path('profile/dashboard/all-video-post/', AllVideosView, name='allvideopost'),
    
    path('profile/dashboard/all-image-post/', AllImagesView, name='allimagepost'),
    path('profile/dashboard/image-post/', ImagePostView, name='imagepost'),
    path('profile/dashboard/video-post/', VideoPostView, name='videopost'),
    path('profile/dashboard/save-post/<str:post_category>', SavePostView, name="save-post"),
    path('profile/dashboard/edit-post/<str:post_category>/<str:Id>/', EditPostView, name="edit-post"),
    path('profile/dashboard/update-post/<str:post_category>/<str:Id>/', UpdatePostView, name="update-post"),
    path('profile/dashboard/delete-post/<str:post_category>/<str:Id>/', DeletePostView, name="delete-post"),
    path('profile/dashboard/publish-post/<str:post_category>/<str:Id>/', PublishPostView, name="publish-post"),
    path('profile/dashboard/unpublish-post/<str:post_category>/<str:Id>/', UnPublishPostView, name="unpublish-post"),
    path('profile/dashboard/published-post/<str:post_category>/', PublishedPostView, name="published-post"),
    path('like/', LikeBtnView,name="likebtn"),
 ]

Store/urls.py
from django.urls import path
from .views import AllProductsView, StoreView

app_name = 'store'
urlpatterns = [
    path('profile/dashboard/store/', StoreView, name='store'),
    path('profile/dashboard/all-product-post/', AllProductsView, name='allproductpost'),
]

zocaya_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from General.views import ProfileFilterView, UserProfilePages, Follow, Unfollow, PostsDetailPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls', namespace='posts')),
    path('', include('General.urls', namespace='generals')),
    path('', include('Dashboard.urls', namespace='dashboards')),
    path('', include('Store.urls', namespace='store')),
    path('', include('paymentgateway.urls', namespace='paymentgateway')),
    path('accounts/', include('allauth.urls')),
    path('<str:username>/', ProfileFilterView, name="profile-filter"),
    path('<str:username>/user-profile/<str:type>/', UserProfilePages, name="userprofilepages"),
    path('follow/<str:username>', Follow, name="followpage"),
    path('unfollow/<str:username>', Unfollow, name="unfollowpage"),
    path('post/<str:username>/<str:type>/<str:post_id>', PostsDetailPage, name="postsdetailpage"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User
from General.models import *
import datetime

class StoreItem(models.Model):
    Id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    Owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    User = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    Image = models.ImageField()
    Headline = models.CharField(max_length=50)
    Description =  models.TextField()
    Price = models.FloatField()
    Published=models.BooleanField(default=False)
    Created_on = models.DateTimeField(default=datetime.datetime.now)
    Updated_on = models.DateTimeField(default=datetime.datetime.now)
    Like_count = models.IntegerField(default=0)

Store/views.py
from django.shortcuts import render
from .models import *
from Posts.models import ImageTrace
from General.models import Profile
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


@login_required(login_url='/')
def StoreView(request):
    my_user = request.user
    profile=Profile.objects.get(user=my_user, Profile_incomplete=False)
    if profile.Account_activated:
        trace=ImageTrace.objects.filter(User=my_user,type='products')
        if not trace.exists():
                        trace=ImageTrace.objects.create(User=my_user,type='products')
                        trace.save()
        else:
            trace.update(Last_Image_Upload="",Current_Image="")
        context = {
            'id':profile.Id,
            'profile':profile,
            'visitor':request.user
        }
        return render(request, 'Store/store.html', context)
    else:
        return redirect('general:verify')


def AllProductsView(request):
    my_user = request.user
    #If you want to know if the user is logged in
    is_user_logged = my_user.is_authenticated
    profile=Profile.objects.get(user=my_user, Profile_incomplete=False)
    if is_user_logged:
        items=StoreItem.objects.filter(User=my_user,Published=False)
        print("------------------------------")
        print(items)
        p = Paginator(items.order_by('-Created_on'), 9)
        page_num = request.GET.get('page', 1)
        page = p.page(page_num)
        context={
            "products": items,
            "pagination": page,
            "profile":profile,
             'visitor':request.user
        }

        return render(request,'Store/allitems.html', context)

Store/templates/Store/allitems.html
{% extends "Dashboard/Dashboard-base.html" %}

<!-- ! --------! -->{% block content %}
<div class="container">

    <ul class="nav nav-tabs justify-content-center">
        <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'post:mypost' %}"> Article Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link  " href="{% url 'post:allimagepost' %}">Image Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'post:allvideopost' %}">Video Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link  active" href="{% url 'store:allproductpost' %}">Products</a>
        </li>
    </ul>

</div>
<section>
    <div class="container">
        <div class="d-flex justify-content-center">

            {% if in_publish %}

            <a href="{% url 'post:published-post' 'product' %}" class="btn btn-outline-success active btn-sm mx-3 active">Published</a>
            <a href="{% url 'store:allproductpost'  %}" class="btn btn-outline-warning  btn-sm mx-3">Un-Published</a> {% else %}
            <a href="{% url 'post:published-post' 'product' %}" class="btn btn-outline-success  btn-sm mx-3">Published</a>
            <a href="" class="btn btn-outline-warning active btn-sm mx-3">Un-Published</a> {% endif %}
        </div>
        <div class="row ">
            {% if products %} {% for post in products %}

            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4" style="display: inline-flex;flex-wrap:nowrap;">
                <div class="card my-5">
                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        <img src="{{post.Image.url}}" class="img-fluid" />
                        <a>
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                    <div class="card-body justify-content-center">
                        <h5 class="card-title">{{post.Headline}}</h5>
                        <p class="card-text">
                            {{post.Description}}
                        </p>
                        <h4>Price : {{post.Price}}/- INR</h4>

                    </div>
                    <div class="card-footer bg-transparent border-info d-flex justify-content-around px-1 py-2">

                        <a href="/profile/dashboard/edit-post/product/{{post.Id}}/" class="btn btn-info">Edit</a>
                        <a type="button" class="btn btn-success" data-toggle="modal" data-target="#publishModal{{ forloop.counter }}">Publish</a>
                        <a type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ forloop.counter }}">Delete</a>
                    </div>

                </div>
            </div>


            {% endfor %} {% else %} {% for post in published_products %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4" style="display: inline-flex;flex-wrap:nowrap;">
                <div class="card my-5">
                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        <img src="{{post.Image.url}}" class="img-fluid" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                    <div class="card-body justify-content-center">
                        <h5 class="card-title">{{post.Headline}}</h5>
                        <p class="card-text">
                            {{post.Description}}
                        </p>

                    </div>
                    <h4>Price : {{post.Price}}/- INR</h4>
                    <div class="card-footer bg-transparent border-info d-flex justify-content-start px-1 py-2">


                        <a type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#unpublishModal{{ forloop.counter }}">Un-Publish</a>

                    </div>
                </div>
            </div>
            {% endfor %}{% endif %}
        </div>

        {% if pagination and pagination.has_next or pagination.has_previous %}

        <nav aria-label="Page navigation example text-center">
            <ul class="pagination justify-content-center  mt-4 ">
                {% if pagination.has_previous %}
                <li class="page-item">
                    <a class="page-link text-info" href="?page={{pagination.previous_page_number}}" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link bg-info" href="?page={{ pagination.number }}">{{ pagination.number }}</a>
                </li>
                {% if pagination.has_next %}
                <li class="page-item text-info">
                    <a class="page-link" href="?page={{pagination.next_page_number}}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>

        {% endif %}
    </div>


    <!-- !--------------- -->
    {% if products %}
    <!-- * -->
    {% for post in products %}
    <div class="modal fade" id="deleteModal{{forloop.counter}}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-danger text-light">
                    <h5 class="modal-title" id="deleteModalLabel{{forloop.counter}}">Confrm Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                </div>
                <div class="modal-body">
                    Are You Sure You Want To Delete The Post It cannot Be Restored Again ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info btn-sm" data-dismiss="modal">Cancel</button>
                    <a href="/profile/dashboard/delete-post/product/{{post.Id}}/" type="button" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="publishModal{{forloop.counter}}" tabindex="-1" aria-labelledby="publishModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-success text-light">
                    <h5 class="modal-title" id="publishModalLabel{{forloop.counter}}">Publish Now ?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                </div>
                <div class="modal-body">
                    Are You Sure ,You Want To Publish The Post ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info btn-sm" data-dismiss="modal">Cancel</button>
                    <a href="/profile/dashboard/publish-post/product/{{post.Id}}/" type="button" class="btn btn-success btn-sm">Publish Now</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %} {% else %}
    <!-- ! -->
    {% for post in published_products %}

    <div class="modal fade" id="unpublishModal{{forloop.counter}}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-warning text-light">
                    <h5 class="modal-title" id="deleteModalLabel{{forloop.counter}}">Confirm Unpublish? </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are You Sure You Want To Unpublish The Post It will not be shown on your public profile ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-info btn-sm" data-dismiss="modal">Cancel</button>
                    <a href="/profile/dashboard/unpublish-post/product/{{post.Id}}/" type="button" class="btn btn-warning btn-sm">Unpublish</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %} {% endif %}

</section>


{% endblock content %}

Store/templates/Store/store.html
{% extends "Dashboard/Dashboard-base.html" %}

<!-- ! --------! -->
{% block content %}
<div class="container">
    {% if message %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Added Successfully</strong> Go <a href="{% url 'post:mypost' %}" class="text-info">Here</a> To Edit Or Publish Your Content
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %} {% if not product %}
    <ul class="nav nav-tabs justify-content-center">
        <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'post:createpost' %}"> Article Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'post:imagepost' %}">Image Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'post:videopost' %}">Video Post</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'store:store' %}">Products</a>
        </li>
    </ul>
    {% endif %}
</div>


<div class="container px-5">
    {% if product %}
    <form action="/profile/dashboard/update-post/product/{{product.Id}}/" method="post">
        {% else %}
        <form method="POST" action="{% url 'post:save-post' 'product'%}">
            {% endif %}
            <!-- ! -->
            {% csrf_token %}
            <div class="input-group mb-2">
                <span class="input-group-text" id="inputGroup-sizing-default">Title</span>
                <input type="text" name="headline" value="{{product.Headline}}" required class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>

            <div class="input-group my-3 ">
                {% if product %}
                <img class="img-thumbnail mr-5" id="feature_image" width="60%" src="{{product.Image.url}}"> {% else %}
                <img class="img-thumbnail mr-5" style="display: none;" id="feature_image" width="60%"> {% endif %}
                <div class="form-group">
                    <label for="image_uploader">Upload Product Image</label>
                    <div style="display: none;" class="my-3 spinner-border text-info" id="image_spinner" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                    {% if product %}
                    <input style="display:none;" type="text" id="img-backup" name="img-backup" value="{{img_name}}">
                    <!-- ! -->
                    {% endif %}
                    <input type="file" accept="image/*" name="image" class="form-control-file" id="image_uploader">
                    <p class="mt-1 text-muted">Only PNG,JPEG and JPG Format Allowed Of Max Size 3Mb </p>
                </div>
            </div>

            <div class="mb-3">
                <textarea class="form-control" name="blog" placeholder="Description Of Product" id="exampleFormControlTextarea1" rows="3">{{product.Description}}</textarea>
            </div>
            <div class="input-group mb-2">
                <span class="input-group-text" id="inputGroup-sizing-default">Price in INR</span>
                <input type="text" name="price" value="{{product.Price}}" required class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>

            {% if product %}
            <button type="submit" class="mt-2 btn btn-outline-info">Update</button> {% else %}
            <button type="submit" class="mt-2 btn btn-outline-info">Add Product</button> {% endif %}
        </form>
</div>

{% endblock content %}
<!-- ! -->
{% block script %}
<script>
    var input = document.getElementById("image_uploader")
    let spinner = document.getElementById("image_spinner")
    let image = document.getElementById("feature_image")
    var id = "{{id}}";
    id = id.replaceAll('-', '')
    input.addEventListener('change', () => {
        var size = parseFloat(input.files[0].size / 1024).toFixed(2);
        if (size > 3000) {
            alert("Please Upload Images Less Than 3mb , Your Supporters Will See Full Quality Images ")
            return
        }

        console.log("In File Upload")
        var data = new FormData()
        for (const file of input.files) {
            data.append('files', file, file.name)
        }

        fetch(`/profile/save-image/products/${id}`, {
            method: 'POST',
            body: data
        }).then(res => res.json()).then(response => {
            spinner.style.display = "none"

            let src = response['src']
            image.style.display = "block"
            image.src = response['src']
        });




    });
</script>
{% endblock script %}