General/urls.py
from django.urls import path
from .views import *

app_name = 'general'
urlpatterns = [
    path('', LoginForm, name='login'),
    path('profile/logout/', logout, name='logout'),
    path('profile/signup/', signup, name='signup'),
    path('profile/verify/', Verify, name='verify'),
    path('profile/generate-otp/', GenerateOtp, name='generateotp'),
    path('signup/create-profile/', CreateProfile, name='profile'),
    path('profile/change-password/', ChangePassword, name='passwordreset'),
    path('profile/change-avatar/', ChangeAvatar, name='changeavatar'),
    path('profile/edit-profile/', EditProfile, name='editprofile'),
    path('profile/save-image/<str:location>/<str:prof_id>', SaveImage, name='saveimage'),
    path('testurl/', TestUrl, name='testurl'),
    path('post/<str:username>/<str:type>/<str:post_id>/', PostsDetailPage, name='testurl'),
    
    path('notifications/mark-as-read/<str:notifi_id>/<str:userprofile_id>', MarkAsRead, name='markasread'),
    path('notifications/mark-allas-read/<str:userprofile_id>', MarkAllAsRead, name='markallasread'),
    path('change/email-number/', ChangeEmailNumber, name='change_email_number'),
    path('profile/edit-profile/banksettings/', BankSetting, name='banksetting'),
    path('profile/edit-profile/editbanksettings/', BankEditSetting, name='editbanksetting'),
    path('profile/edit-profile/publicProfileSetting/', PublicProfileSetting, name='publicprofilesetting'),
    path('profile/edit-profile/publicProfileSettingDone/', PublicProfileSettingDone, name='publicprofilesettingdone'),
    path('profile/update-shipping-addr/<str:product_id>/<str:creator_profileId>', UpdateShippingAddr, name='updateshippingaddr'),
]

Posts/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('profile/dashboard/create-post/', CreatePostView, name='createpost'),
    path('profile/dashboard/my-post/', MyPostView, name='mypost'),
    path('profile/dashboard/delete-post/', DeletePostView, name='deletepost'),
    path('profile/dashboard/all-video-post/', AllVideosView, name='allvideopost'),
    
    path('profile/dashboard/all-image-post/', AllImagesView, name='allimagepost'),
    path('profile/dashboard/image-post/', ImagePostView, name='imagepost'),
    path('profile/dashboard/video-post/', VideoPostView, name='videopost'),
    path('profile/dashboard/save-post/<str:post_category>', SavePostView, name="save-post"),
    path('profile/dashboard/edit-post/<str:post_category>/<str:Id>/', EditPostView, name="edit-post"),
    path('profile/dashboard/update-post/<str:post_category>/<str:Id>/', UpdatePostView, name="update-post"),
    path('profile/dashboard/delete-post/<str:post_category>/<str:Id>/', DeletePostView, name="delete-post"),
    path('profile/dashboard/publish-post/<str:post_category>/<str:Id>/', PublishPostView, name="publish-post"),
    path('profile/dashboard/unpublish-post/<str:post_category>/<str:Id>/', UnPublishPostView, name="unpublish-post"),
    path('profile/dashboard/published-post/<str:post_category>/', PublishedPostView, name="published-post"),
    path('like/', LikeBtnView,name="likebtn"),
 ]

zocaya_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from General.views import ProfileFilterView, UserProfilePages, Follow, Unfollow, PostsDetailPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls', namespace='posts')),
    path('', include('General.urls', namespace='generals')),
    path('', include('Dashboard.urls', namespace='dashboards')),
    path('', include('Store.urls', namespace='store')),
    path('', include('paymentgateway.urls', namespace='paymentgateway')),
    path('accounts/', include('allauth.urls')),
    path('<str:username>/', ProfileFilterView, name="profile-filter"),
    path('<str:username>/user-profile/<str:type>/', UserProfilePages, name="userprofilepages"),
    path('follow/<str:username>', Follow, name="followpage"),
    path('unfollow/<str:username>', Unfollow, name="unfollowpage"),
    path('post/<str:username>/<str:type>/<str:post_id>', PostsDetailPage, name="postsdetailpage"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

General/views.py
from django.shortcuts import render,redirect
from django.contrib import auth, messages
from .models import *
from Posts.models import *
from Store.models import *
from django.core.files.storage import FileSystemStorage
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from zocaya_new.settings import *
# from Zocaya.settings import *
import json,uuid
from Posts.models import Notification
import time, threading
from django.core.mail import send_mail
import random
from django.core.paginator import Paginator
from django.template import loader
from imagekitio import ImageKit
from media import *

imagekit = ImageKit(
    private_key='private_lLLidL7grmjC6y/uuR98dEGlvPM=',
    public_key='public_2e8JMemRIR9zGN+aIQB3dSRPnK0=',
    url_endpoint='https://ik.imagekit.io/xfu94rzcsoi/'
)


def UpdateShippingAddr(request,product_id,creator_profileId):
    if request.user.is_authenticated:
      shiping_addr=ShippingAddress.objects.filter(User=request.user)
      if request.method=='POST':
        state=request.POST['state']
        pincode=request.POST['pincode']
        city=request.POST['city']
        address=request.POST['address']
        shiping_addr.update(
            address_line=address,
            state=state,
            pin_code=pincode,
            city=city
        )
        customer_profileId=Profile.objects.get(user=request.user).Id.hex
        return redirect("paymentgateway:paymentgateway",creator_profileId,customer_profileId,product_id)
    
    else:
        return redirect("general:login")

def LoginForm(request):
    my_user = request.user
    #If you want to know if the user is logged in
    is_user_logged = my_user.is_authenticated
    if is_user_logged:
        return redirect('dashboard:dashboard')
    if request.method=="POST":
        email=request.POST['uname']
        try:
            uname=User.objects.get(email=email).username
        except:
            return render(request,'General/index.html',{'error':'Invalid Email Address'})
        pwd=request.POST['pass']
        user=auth.authenticate(username=uname,password=pwd)
        if user is not None:
            auth.login(request,user)
            return redirect(request.path)
        else:
            return render(request,'General/index.html',{'error':'Invalid Credentials'})
    return render(request,'General/index.html')

    # return render(request, 'General/login.html', {})


def signup(request, backend='django.contrib.auth.backends.ModelBackend'):
     if request.method=="POST":
          # Create a user
          print("ok1")
     
          if request.POST['pass']==request.POST['passConfirm']:
               print("ok2")
               # Both the passwords have been matched
               # Now check if user exist or not
               try:

                    username = request.POST['username']
                    print("ok2")
                    if " " in username:
                        return render(request,'General/signup.html',{'error':'username cannot have spaces'})
                        
                    user=User.objects.get(username=username)
                    return render(request,'General/signup.html',{'error':'user already exist'})
                    
               except User.DoesNotExist:
                    try:
                        print("ok3")
                        email=request.POST['email']
                        temp=User.objects.get(email=email)
                        return render(request,'General/signup.html',{'error':'Email exist'})
                    except:
                        print("ok4")
                        user=User.objects.create_user(username=request.POST['username'],
                                                    password=request.POST['pass'],
                                                    email=email
                                                    )                                        
                        auth.login(request,user, backend='django.contrib.auth.backends.ModelBackend')
                        print(user)
                        return redirect('general:profile')
          else:
               return render(request,'General/signup.html',{'error':'password does not match'})
                                 
     return render(request,'General/signup.html')

def Verify(request):
    my_user=request.user
    if request.method=="POST":
        otpMail=request.POST['otpmail']
        # otpSms=request.POST['otpsms']
        print(otpMail)
        # print(otpSms)
        profile=Profile.objects.get(user=my_user)
        if int(profile.otp_for_email)==int(otpMail):
            Profile.objects.filter(user=my_user).update(Account_activated=True)
            return redirect('dashboard:dashboard')
        else:
             return render(request,'General/otpEmail.html',{'profile':profile,'message':'Invalid OTP,Please Try Again'})
            
            
    if my_user.is_authenticated:
        profile=Profile.objects.get(user=my_user)
        if not profile.Account_activated:
            return render(request,'General/otpEmail.html',{'profile':profile})
        else:
            return redirect('dashboard:dashboard')
        
@csrf_exempt
def GenerateOtp(request):
    my_user=request.user
    print(my_user)
    profile=Profile.objects.get(user=my_user)
    print(my_user)
    if request.method=='POST' and my_user.is_authenticated and profile.otp_for_email==0 :
        print("ok",my_user)
        received_json_data= json.loads(request.body)
        username=received_json_data['username']    
        thread=threading.Thread(target=create_timeout,args=(username,))
        thread.start()
        account_sid = 'xxxxxxxxxxxxxxxxxxx'
        auth_token = 'xxxxxxxxxxxxxxxxxxxxxxxx'
        # client = Client(account_sid, auth_token)
        # otp_mob=random.randint(111111,999999)
        otp_mail=random.randint(111111,999999)
        Profile.objects.filter(user=my_user).update(otp_for_email=otp_mail)
        # message = client.messages \
        #                 .create(
        #                     body="Your OTP is "+str(otp_mob),
        #                     from_='+xxxxx33',
        #                     to=str(profile.Phone_no)
        #                 )
        send_mail(
        "Verification Mail",
        "Hi Zocaya User\nYour Zocaya OTP is :"+str(otp_mail)+"\n\n You are receiving this OTP because your email has been used to sign up on zocaya.com\n\nIf you have not signed up on zocaya, please contact us on zocayamedia@gmail.com and we will investigate the issue further \n\n Thanks,\nZocaya Team",
        "zocayamedia@gmail.com",
        [str(profile.user.email)],
        fail_silently=True
            )
        print(username)
        return JsonResponse({'success':True})
    else:
        return JsonResponse({'success':False}) 

@login_required(login_url='/')
def ChangeEmailNumber(request):
    my_user=request.user
    if my_user.is_authenticated:
            if request.method=='POST':
                email=request.POST['mail']
                # mob_no=request.POST['number']
                User.objects.filter(username=my_user).update(email=email)
                # Profile.objects.filter(user=my_user).update(Phone_no=mob_no)
                profile=Profile.objects.get(user=my_user)
                return render(request,'General/changeEmailNumber.html',{'profile':profile,'message':'change successfully!'})
            else:
                profile=Profile.objects.get(user=my_user)
                return render(request,'General/changeEmailNumber.html',{'profile':profile})
    else:
            return redirect('general:login')
@login_required(login_url='/')
def logout(request):
    my_user = request.user
        #If you want to know if the user is logged in
    is_user_logged = my_user.is_authenticated
    if is_user_logged:
        auth.logout(request)
    return redirect('general:login')

@login_required(login_url='/')
def CreateProfile(request):
    my_user = request.user

    profile = Profile.objects.filter(Profile_incomplete=False, user=my_user)
    if profile.exists():
        return redirect('dashboard:dashboard')
    else:
        if request.method=="POST":

            if 'dp_input' in request.FILES:
                f=request.FILES
                f = f['dp_input']

                upload = imagekit.upload(
                    file=open(f.temporary_file_path(), "rb"),
                    file_name="image-post/" + str(my_user.email) + "/" + str(f),
                    options={
                        "response_fields": ["is_private_file", "tags"],

                    },
                )
                src = upload['response']['url']
                fileid=upload['response']['fileId']
            else:
                upload = imagekit.upload(
                    file=open('./media/avatar.jpg', "rb"),
                    file_name="image-post/" + str(my_user.email) + "/" +'dp',
                    options={
                        "response_fields": ["is_private_file", "tags"],

                    },
                )
                src = upload['response']['url']
                fileid = upload['response']['fileId']

            profile=Profile.objects.create(
                Name= request.POST['username'],
                username= my_user.username,
                Gender = request.POST['gender'],
                UserType=request.POST['usertype'],
                user = my_user,
                Avatar=src,
                fileid=fileid,
                DateOfBirth = request.POST['dob'],
                URL="/"+str(my_user),
                tab_order='image,videos,articles',
                Country = request.POST['country'],
                
                Phone_no = request.POST['num'],
                Bio = request.POST['aboutme'],
                Profile_incomplete=False,
            )

General/templates/General/change-avatar.html
{% extends "Dashboard/Dashboard-base.html" %}

<!-- ! --------! -->
{% block content %}

<div class="mt-5 pt-3">
    {% if message %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
</div>

<ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
        <a class="nav-link " href="/profile/edit-profile/">General Profile Settings</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active " aria-current="page" href="{% url 'general:changeavatar' %}">Change Avatar</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'general:passwordreset' %}">Change Password</a>
    </li>
    {% if not banksetting.exists %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'general:banksetting' %}">Bank Setting</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'general:editbanksetting' %}">Edit Bank Setting</a>
    </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'general:publicprofilesetting' %}">Subscription Settings</a>
    </li>
</ul>

<div class="container ">
    <h2 class="text-left mt-5">Change Profile Pic</h2>
    <form method="POST" action="{% url 'general:changeavatar' %}" enctype="multipart/form-data"> {% csrf_token %}

        <img src="{{profile.Avatar}}" width="170px" height="170px" id="dp" class="rounded-circle mt-5">
        <div class="form-group mt-2 mb-5">
            <label for="image_uploader">Profile Pic</label>
            <div style="display: none;" class="spinner-border text-info" id="image_spinner" role="status">

            </div>
            <input type="file" accept="image/*" name="image" class="form-control-file" id="image_uploader">
            <p class="mt-1 text-muted">Only PNG,JPEG and JPG Format Allowed Of Max Size 3Mb </p>
            <button class="btn btn-sm btn-outline-info mt-5">Save Image</button>
        </div>
    </form>
</div>
{% endblock content %} {% block script %}
<script>
    var input = document.getElementById("image_uploader")
    let spinner = document.getElementById("image_spinner")
    let image = document.getElementById('dp')
    var id = '{{id}}';
    input.addEventListener('change', () => {
        var size = parseFloat(input.files[0].size / 1024).toFixed(2);
        if (size > 3000) {
            alert("Please Upload Images Less Than 3mb , Your Supporters Will See Full Quality Images ")
            return
        }
        console.log("In File Upload")
        var data = new FormData()
        for (const file of input.files) {
            data.append('files', file, file.name)
        }
        spinner.style.display = ""
        fetch(`/profile/save-image/avatar/${id}`, {
            method: 'POST',
            body: data
        }).then(res => res.json()).then(response => {
            spinner.style.display = "none"

            let src = response['src']
            image.style.display = "block"
            image.src = response['src']
        });




    });
</script>
{% endblock script %}

General/templates/General/editBankSetting.html
{% extends "Dashboard/Dashboard-base.html" %}

<!-- ! --------! -->
{% block content %}

<div class="mt-5 pt-3">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %} {% endif %}
</div>
<ul class="nav nav-tabs justify-content-center">
    <li class="nav-item">
        <a class="nav-link " href="/profile/edit-profile/">General Profile Settings</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'general:changeavatar' %}">Change Avatar</a>
    </li>
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'general:passwordreset' %}">Change Password</a>
    </li>
    {% if not banksettings.exists %}
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'general:banksetting' %}">Bank Setting</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'general:editbanksetting' %}">Edit Bank Setting</a>
    </li>
    {% endif %}
    <!--
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'general:editbanksetting' %}">Edit Bank Setting</a>
    </li> -->
    <li class="nav-item">
        <a class="nav-link " aria-current="page" href="{% url 'general:publicprofilesetting' %}">Subscription Settings</a>
    </li>
</ul>

<div class="container mt-5">
    <h3>Require Your Bank Info To Transfer Funds Straight Into Your Account</h3>
    <p class="text-muted">We Never Missuse Your Given Info</p>
    <form method="POST" action="/profile/edit-profile/editbanksettings/" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">Bank Account Number</label>
            <input type="text" name="AccNum" value="{{banksetting.Account_Number}}" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">IFSC Code</label>
            <input type="text" name="code" value="{{banksetting.IFSC_Code}}" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Account Holder Name</label>
            <input type="text" name="AccName" value="{{banksetting.Account_holder_name}}" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">

        </div>
        <label for="address">Address</label>
        <div class="row" id="address">
            <div class="col">
                <input type="text" name="street" value="{{banksetting.Street_Address}}" class="form-control  form-control-sm " placeholder="Street">
            </div>
            <div class="col">
                <input type="text" name="city" value="{{banksetting.City}}" class="form-control  form-control-sm" placeholder="City">
            </div>
        </div>
        <div class="row mt-3">
            <div class="col">
                <input type="text" name="state" value="{{banksetting.State}}" class="form-control  form-control-sm " placeholder="State">
            </div>
            <div class="col">
                <input type="text" name="pincode" value="{{banksetting.Pincode}}" class="form-control  form-control-sm" placeholder="Pincode">
            </div>
        </div>

        <button type="submit" class="btn btn-outline-info btn-sm mt-4">Submit</button>
    </form>
</div>
{% endblock content %}

General/templates/General/imagedetailpage.html
{% extends "General/user-profile-base.html" %}
<!-- ! -->
{% block content %}

<hr>

<div class="container width_req">
    {% if content.Is_free %}
    <img style="width: 80%;" src="{{ content.Image }}" class="img-fluid " alt="">
    <h2 class="my-2" style="width: 80%;">{{ content.Headline }}</h2>
    <p style="width: 80%; font-size: 18px;" class="mt-3 text-secondary text-justify">{{ content.Description }}</p>


    {% else %} {% if visitor in content.Owner.My_subscribers.all %}
    <img style="width: 80%;" src="{{ content.Image }}" class="img-fluid " alt="">
    <h2 class="my-2" style="width: 80%;">{{ content.Headline }}</h2>
    <p style="width: 80%; font-size: 18px;" class="mt-3 text-secondary text-justify">{{ content.Description }}</p>
    {% else %} {% ifequal visitor content.Owner.user %}
    <img src="{{ content.Image }}" class="img-fluid " alt="">
    <h2 class="my-2" style="width: 80%;">{{ content.Headline }}</h2>
    <p class="text-muted">For Paid Subscribers Only</p>
    <p style="width: 80%; font-size: 18px;" class="mt-3 text-secondary text-justify">{{ content.Description }}</p>
    {% else %}
    <img style="width: 80%;" src="/images/lock.jpg" class="img-fluid " alt=""> {% endifequal %}{% endif %}{% endif %}
    <div class="blockquote-footer mt-5">
        <h5>Author</h5> <cite title="Source Title">{{ profile.username }}</cite>

    </div>
    <a href="/{{ profile.username }}" class="text-info ">Visit Profile
        <svg class="ml-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-right-square-fill" viewBox="0 0 16 16">
        <path d="M14 0a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12zM5.904 10.803L10 6.707v2.768a.5.5 0 0 0 1 0V5.5a.5.5 0 0 0-.5-.5H6.525a.5.5 0 1 0 0 1h2.768l-4.096 4.096a.5.5 0 0 0 .707.707z"/>
      </svg></a>
</div>

<!-- ! -->
{% endblock content %}

General/templates/General/otpEmail.html
 {% load static %} {% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="Zocaya Sign up - Independent Artist Directly Paid by Patreon">
    <meta name="description" content=": Zocaya Sign up allows Independent artists to start their private club for paying fans and show their photos, videos directly. No need for Ads, No demonetised videos">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Zocaya</title>
<link rel="shortcut icon" type="image/jpeg" href="/static/favicon.jpeg"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-184520943-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-184520943-1');
    </script>
    <!-- Facebook Pixel Code -->
    <script>
        ! function(f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function() {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '489931002145673');
        fbq('track', 'PageView');
    </script>
    <noscript>
 <img height="1" width="1" 
src="https://www.facebook.com/tr?id=489931002145673&ev=PageView
&noscript=1"/>
</noscript>
    <!-- End Facebook Pixel Code -->
</head>

<body>

    <div class="hero_section">

        <div id="hero_img">
            <img src="{% static 'images/Transparent2.png' %}" alt="">
            <p><b>What is Zocaya? </b>The best place for businesses and creators to start a private club membership service.</p>
            <p><b>How?</b> Provide best products or content to your best supporters with a simple monthly membership service.
            </p>

        </div>

        <div class="login_form">




            <div class="form_block">
                <form method="POST" action=".">
                    {% csrf_token %}
                    <h2 class="mb- mr-3"> Verify Your Email</h2>
                    <div id="alert-otp" class="alert alert-success alert-dismissible fade show" style="display: none;" role="alert">
                        <strong>Success!</strong> OTP Send.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% if message %}
                    <div id="alert-otp" class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>Fail!</strong> {{message}}.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}

                    <p class="text-muted">{{profile.user.email}}</p>

                    <a class="tex-info" href="{% url 'general:change_email_number' %}">Change Email</a>



                    <div>
                        <input type="text " class="form-control " name="otpmail" placeholder="Enter OTP From Email " aria-label="Recipient 's username" aria-describedby="button-addon2">

                        <button style="width: 100%;" class="btn btn-outline-success mt-3 btn-block" type="button" id="sendOTP_button">
                            <span id="send_otp_text">Send OTP</span>
                            <div style="display: none;" class="spinner-border text-success spinner-border-sm" id="otp_spinner" role="status">
                                <span class="visually-hidden">Loading...</span>
                            </div>
                        </button>
                        <button style="width: 45%;" class="btn btn-outline-info mt-3 btn-block" type="submit" id="conferm_button">Confirm</button>
                        <a id="logout_link" style="width: 45%; float:right;" class="btn btn-outline-danger mt-3 btn-block" href="{% url 'general:logout' %} " type="submit" id="conferm_button">Logout</a>
                    </div>
                    <div id="timer" style="display: none;" class="text-muted mt-3">

                        valid for 2 mins Resend OTP in <span id="time"></span> sec
                    </div>


                    <form/>
            </div>



        </div>
    </div>

    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

</body>
<script defer type="text/javascript">
    window.onload = myFunction();

    function myFunction() {
        console.log("IN FUNCTION")
        let time = 120
        let time_view = document.getElementById('time')
        let sendOTP_button = document.getElementById('sendOTP_button')
        let logout_link = document.getElementById('logout_link')
        let otp_spinner = document.getElementById('otp_spinner')
        let alert_otp = document.getElementById('alert-otp')
        let notallowed = sendOTP_button.classList.contains('disabled')
        let data = {
            username: '{{profile.username}}'
        }

        function sendOTP() {
            time = 120
            otp_spinner.style.display = ""
            alert_otp.style.display = "none"
            console.log("In Send OTP")
            if (!notallowed) {


                otp_spinner.style.display = ""
                sendOTP_button.classList.toggle('disabled')
                logout_link.classList.toggle('disabled')
                fetch('/profile/generate-otp/', {
                    method: 'POST',
                    body: JSON.stringify(data)
                }).then(response => response.json()).then(json => {
                    console.log(json)
                    if (json['success']) {
                        otp_spinner.style.display = "none"
                        alert_otp.style.display = ""
                        alert("OTP Send Successfully!")
                        document.getElementById('timer').style.display = "";
                        var id = window.setInterval(function() {
                            time = time - 1
                            time_view.innerHTML = time
                            if (time <= 0) {
                                sendOTP_button.classList.toggle('disabled')
                                logout_link.classList.toggle('disabled')
                                otp_spinner.style.display = "none"

                                window.clearInterval(id)
                            }

                        }, 1000);
                    } else {
                        alert("Please Wait For 2 mins before sending another otp")
                        otp_spinner.style.display = "none"
                        alert_otp.style.display = ""
                    }
                })




            }
        }

        console.log(sendOTP_button)
        sendOTP()
        sendOTP_button.addEventListener('click', sendOTP);

        function my_onkeydown_handler(event) {
            switch (event.keyCode) {
                case 116: // 'F5'
                    event.preventDefault();
                    event.keyCode = 0;
                    window.status = "F5 disabled";
                    break;
            }
        }
        document.addEventListener("keydown", my_onkeydown_handler);
    }
</script>

</html>