Dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('profile/dashboard/', DashboardView, name='dashboard'),
    path('profile/dashboard/your-supporting', YourSupporting, name='yoursupporting'),
    path('profile/dashboard/followers/', FanpageView, name='fanpage'),
    path('profile/dashboard/Search/', SeachpageView, name='searchpage'),
    path('profile/dashboard/memberships/', Memberships, name='memberships'),
    path('profile/dashboard/redeem/', RedeemPage, name='redeempage'),
]

Posts/urls.py
from django.urls import path
from .views import *

app_name = 'post'
urlpatterns = [
    path('profile/dashboard/create-post/', CreatePostView, name='createpost'),
    path('profile/dashboard/my-post/', MyPostView, name='mypost'),
    path('profile/dashboard/delete-post/', DeletePostView, name='deletepost'),
    path('profile/dashboard/all-video-post/', AllVideosView, name='allvideopost'),
    
    path('profile/dashboard/all-image-post/', AllImagesView, name='allimagepost'),
    path('profile/dashboard/image-post/', ImagePostView, name='imagepost'),
    path('profile/dashboard/video-post/', VideoPostView, name='videopost'),
    path('profile/dashboard/save-post/<str:post_category>', SavePostView, name="save-post"),
    path('profile/dashboard/edit-post/<str:post_category>/<str:Id>/', EditPostView, name="edit-post"),
    path('profile/dashboard/update-post/<str:post_category>/<str:Id>/', UpdatePostView, name="update-post"),
    path('profile/dashboard/delete-post/<str:post_category>/<str:Id>/', DeletePostView, name="delete-post"),
    path('profile/dashboard/publish-post/<str:post_category>/<str:Id>/', PublishPostView, name="publish-post"),
    path('profile/dashboard/unpublish-post/<str:post_category>/<str:Id>/', UnPublishPostView, name="unpublish-post"),
    path('profile/dashboard/published-post/<str:post_category>/', PublishedPostView, name="published-post"),
    path('like/', LikeBtnView,name="likebtn"),
 ]

paymentgateway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from paymentgateway.views import *

app_name = 'paymentgateway'
urlpatterns = [
     path('payment/webhook/', Webhook, name='webhook'),



     path('payment/subscribe/<str:creator_username>/', Subscribe, name='subscribe'),
     path('payment/donate/<str:creator_username>/', Donate, name='donation'),
     path('payment/donationvarify/<str:creator_username>/', DonationVerify, name='donationverify'),
     path('payment/cancel-subscription/<str:creator_profileId>/', CancelSubscription, name='cancelsubscription'),
     path('payment/buyproduct/<str:creator_profileId>/<str:customer_profileId>/<str:productId>/', BuyProduct, name='paymentgateway'),
     path('payment/product/thankyou/<str:customer_id>/<str:creator_id>/<str:amount>/<str:productId>', ThankyouForProduct, name='thankyouforproduct'),
     path('payment/redeem/', RedeemAmount, name='redeemamount'),
    
]

zocaya_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from General.views import ProfileFilterView, UserProfilePages, Follow, Unfollow, PostsDetailPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls', namespace='posts')),
    path('', include('General.urls', namespace='generals')),
    path('', include('Dashboard.urls', namespace='dashboards')),
    path('', include('Store.urls', namespace='store')),
    path('', include('paymentgateway.urls', namespace='paymentgateway')),
    path('accounts/', include('allauth.urls')),
    path('<str:username>/', ProfileFilterView, name="profile-filter"),
    path('<str:username>/user-profile/<str:type>/', UserProfilePages, name="userprofilepages"),
    path('follow/<str:username>', Follow, name="followpage"),
    path('unfollow/<str:username>', Unfollow, name="unfollowpage"),
    path('post/<str:username>/<str:type>/<str:post_id>', PostsDetailPage, name="postsdetailpage"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paymentgateway/models.py
from django.db import models
from General.models import Profile
import uuid
import datetime
# Create your models here.
class Plan(models.Model):
    Id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    planName=models.CharField(max_length=100)
    period=models.CharField(max_length=100)
    interval=models.IntegerField(default=1)
    amount=models.IntegerField(default=0)
    description=models.TextField(default=" ")
    planId=models.CharField(max_length=100,default="")
    
    def __str__(self): 
         return str(self.planName)
     
class Subscriptions(models.Model):
     Id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
     Customer_profile=models.ForeignKey(Profile,related_name="customer_subscription",on_delete=models.CASCADE,null=True)
     Creator_profile=models.ForeignKey(Profile,related_name="creator_subscription",on_delete=models.CASCADE,null=True)
     amount=models.FloatField()
     subscriptionId=models.CharField(max_length=200,unique=True,default="")
     subscriptionLink=models.CharField(max_length=200,unique=True,default="")
     planId=models.CharField(max_length=500,default="",null=True)
     status=models.CharField(max_length=100,default="not created")
     cancelled=models.BooleanField(default=False)


class Donations(models.Model):
    Id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    Customer_profile = models.ForeignKey(Profile, related_name="customer_donation", on_delete=models.CASCADE,null=True)
    Creator_profile = models.ForeignKey(Profile, related_name="creator_donation", on_delete=models.CASCADE,null=True)
    amount = models.FloatField()
    order_id = models.CharField(max_length=200, unique=True, null=True)
    payment_id = models.CharField(max_length=200, unique=True, null=True)
    signature= models.CharField(max_length=500, null=True)
    status = models.CharField(max_length=100, default="not created")
    cancelled = models.BooleanField(default=False)
     
class ProductPurchased(models.Model):
     Id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
     Customer_profile=models.ForeignKey(Profile,related_name="customer",on_delete=models.CASCADE,null=True)
     Creator_profile=models.ForeignKey(Profile,related_name="creator",on_delete=models.CASCADE,null=True)
     linkRefrence_id=models.CharField(max_length=100,default="")
     payment_id=models.CharField(max_length=100,default="")
     link_id=models.CharField(max_length=100,default="")
     status=models.CharField(max_length=100,default="")
     amount=models.FloatField(default=0)

     
     
  

paymentgateway/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
import json,requests
from General.models import *
from .models import *
import uuid
import razorpay
import hmac
import datetime
from Store.models import *
from django.template import loader
from zocaya_new import settings
# from Zocaya.settings import *
from django.core.mail import send_mail


# Create your views here.

@csrf_exempt
def Webhook(request):
    if request.method=="POST":
        print("------------------------+++++-----------------------------")
        signature=request.headers['X-Razorpay-Signature']
        client = razorpay.Client(auth=("rzp_test_J9Lxu7OB8M6GR3", "NOj4sb6Sp0YBIG30XLkwOhOc"))
        payload_body = json.dumps(json.loads(request.body), separators=(',', ':'))
        try:        
            client.utility.verify_webhook_signature(payload_body,signature, "Abrar.786ahmed")
            body=json.loads(request.body)
            event=body['event']
            subscriptionId=body['payload']['subscription']['entity']['id']
            print(event)
            print(subscriptionId)
            if event=='subscription.cancelled' or event=='subscription.completed':
                subscriptionObj=Subscriptions.objects.get(subscriptionId=subscriptionId)
                customer=subscriptionObj.Customer_profile
                creator=subscriptionObj.Creator_profile
                customer.Subscribed.remove(creator.user)
                creator.My_subscribers.remove(customer.user)
                customer.save()
                creator.save()
                subscriptionObj.delete()
                return JsonResponse({"success":True})
            elif event=='subscription.activated':
                subscriptionObj=Subscriptions.objects.get(subscriptionId=subscriptionId)
                customer=subscriptionObj.Customer_profile
                creator=subscriptionObj.Creator_profile
                notification=Notification.objects.create(
                                
                                Message="Congratulation! You Got A New Paid Subscriber " +
                                str(customer.username),
                                Link="/"+str(customer.username)
                            )
                notification.Send_to.add(creator.user)
                notification.save()
                return JsonResponse({"success":True})
            elif event=='subscription.charged':
                subscriptionObj=Subscriptions.objects.get(subscriptionId=subscriptionId)
                customer=subscriptionObj.Customer_profile
                creator=subscriptionObj.Creator_profile
                subscriptionObj.status='active'
                subscriptionObj.save()
                customer.Subscribed.add(creator.user)
                customer.Following.add(creator.user)
                creator.My_subscribers.add(customer.user)
                creator.my_followers.add(customer.user)
                creator.Revenue+=round((subscriptionObj.amount/100)*0.92,2)
                creator.save()
                print("revenue----")
                print(creator.Revenue)
                customer.save()
                notification=Notification.objects.create(
                                
                                Message="You Got A New Subscription Amount Of "+str(round((subscriptionObj.amount/100)*0.92,2))+"/-INR From " +
                                str(customer.username),
                                Link="/"+str(customer.username)
                            )
                notification.Send_to.add(creator.user)
                notification.save()
                return JsonResponse({"success":True})
            elif event=='subscription.pending':
                subscriptionObj=Subscriptions.objects.get(subscriptionId=subscriptionId)
                subscriptionObj.status='pending'
                subscriptionObj.save()
                customer=subscriptionObj.Customer_profile
                creator=subscriptionObj.Creator_profile
                send_mail( "Charge Failed","Hi Zocaya User,\nYour recent payment for "+str(subscriptionObj.Creator.username)+" failed. To avoid having your subscription canceled, please complete the payment to change the linked card at:"+str(subscriptionObj.subscriptionLink)+"\n\nRegards,\nZocaya Team", 'zocayamedia@gmail.com',[customer.user.email] ) 
                return JsonResponse({"success":True})
            elif event=='subscription.halted':
                subscriptionObj=Subscriptions.objects.get(subscriptionId=subscriptionId)
                customer=subscriptionObj.Customer_profile
                creator=subscriptionObj.Creator_profile
                send_mail( "Hi user\nAll Charge Attempts Failed","After Regular attempt and due to payment failure we have to cancelled your subscription Thankyou For Using our service!\nTeam Zocaya", 'zocayamedia@gmail.com',[customer.user.email] )
                url = "https://api.razorpay.com/v1/subscriptions/"+subscriptionId+"/cancel"

                payload = json.dumps({
                "cancel_at_cycle_end": 0
                })
                headers = {
                'Content-Type': 'application/json',
                'Authorization': 'Basic cnpwX3Rlc3RfMms1TXF6VW9pSHFoYm46clNjMzdJUlNtWW1lY3Noa3gwZ3U1cWsw'
                }

                response = requests.request("POST", url, headers=headers, data=payload)
                json_response=response.json()
                if json_response['status']!='cancelled':
                        response = requests.request("POST", url, headers=headers, data=payload)
                        return JsonResponse({"success":True})
                       
                else:  
                        return JsonResponse({"success":True})
            else:
                return JsonResponse({"success":True})    
                
                
                                
                
            
        except:
            return JsonResponse({"success":False})
            
@csrf_exempt
def Subscribe(request,creator_username):

  if request.method=='POST':
    print("-----------------PPPPP------------")    
    if request.user.is_authenticated: #authenticate
        try:
            visitor_profile=Profile.objects.get(user=request.user)
        except:
            return JsonResponse({"response":False})
        creator_profile=Profile.objects.get(username=creator_username)
        if creator_profile.user in visitor_profile.Subscribed.all() or visitor_profile==creator_profile:
            return redirect('/'+creator_username+'/')
        amount=creator_profile.Subscription_price
        require_plan=Plan.objects.filter(amount=amount*100)
        subscription=Subscriptions.objects.filter(Customer_profile=visitor_profile,Creator_profile=creator_profile)
        print(subscription[0].planId,)
        if subscription.exists():
           print("In Exist")
           print({'id':subscription[0].subscriptionId,"name":visitor_profile.Name,"email":visitor_profile.user.email,"phone":str(visitor_profile.Phone_no)})
           return JsonResponse({'id':subscription[0].subscriptionId,"name":visitor_profile.Name,"email":visitor_profile.user.email,"phone":str(visitor_profile.Phone_no)})
        if require_plan.exists(): # Check If Plan Already Exists
                plan_id=require_plan[0].planId
                subs_response=create_subscription(plan_id)
                print(subs_response)
                if subs_response['status'] == 'created':
                        subscription=Subscriptions.objects.create(
                            Customer_profile=visitor_profile,
                            Creator_profile=creator_profile,
                            amount=require_plan[0].amount,
                            subscriptionId=subs_response['id'],
                            planId=subs_response['plan_id'],
                            status=subs_response['status'],
                            subscriptionLink=subs_response['short_url']
                            )

                        subscription.save()
                        print("--------  ++++  ++++  ----")
                        return JsonResponse({'id':subscription.subscriptionId,"name":visitor_profile.Name,"email":visitor_profile.user.email,"phone":str(visitor_profile.Phone_no)})
                        
                      
                else:
                    return JsonResponse(subs_response)
 
        
        
        else : # Create Plan If Not Exists
            plan=Plan.objects.create(
            planName=str(amount)+"plan",
            period="monthly",
            interval=1,
            amount=amount*100,
            description="simple plan for creating subscription using razorpay",
            )
            plan.save()
            url = "https://api.razorpay.com/v1/plans"

            payload = json.dumps({
                "period": plan.period,
                "interval": plan.interval,
                "item": {
                    "name": plan.planName,
                    "amount":plan.amount,
                    "currency": "INR",
                    "description": plan.description
                }
                })
            headers = {
                'Content-Type': 'application/json',
                'Authorization': 'Basic    cnpwX3Rlc3RfMms1TXF6VW9pSHFoYm46clNjMzdJUlNtWW1lY3Noa3gwZ3U1cWsw'
            }

            response = requests.request("POST", url, headers=headers, data=payload)
            print("+++++++++++++++++++++++++++++++++++")
            print(response.text)
            res=response.json()
            try:
                res['item']['active']
            except:
                return JsonResponse(res)
            if res['item']['active']: #IF Plan created Successfully
                plan_id=res['id']

paymentgateway/templates/ThankyouForOrder.html
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
    <style>
        @import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
        @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
    </style>
    <link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
    <script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
    <script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
</head>

<body>
    <header class="site-header" id="header">
        <h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
    </header>

    <div class="main-content">
        <i class="fa fa-check main-content__checkmark" id="checkmark"></i>
        <p class="main-content__body" data-lead-id="main-content-body">
            Thanks a for Purchasing We Have Sent Info about Creator On You Mail, You Can Reach Him Directly</p>
    </div>
    <a style="margin-top:100px;" href="{% url 'dashboard:dashboard' %}">BACK TO Home </a>

    <footer class="site-footer" id="footer">
        <p class="site-footer__fineprint" id="fineprint">Copyright Zocaya ©2021 | All Rights Reserved</p>
    </footer>
</body>

</html>

paymentgateway/templates/orderInvoiceEmailTemplate_Creator.html
<html>

<body style="background-color:#e2e1e0;font-family: Open Sans, sans-serif;font-size:100%;font-weight:400;line-height:1.4;color:#000;">
    <table style="max-width:670px;margin:50px auto 10px;background-color:#fff;padding:50px;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;-webkit-box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);-moz-box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); border-top: solid 10px green;">
        <thead>
            <tr>
                <th>

                    <h5>New Purchase From Your Zocaya Account</h5>

                </th>
                <th style="text-align:right;font-weight:400;">{{date}}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="height:35px;"></td>
            </tr>
            <tr>
                <td colspan="2" style="border: solid 1px #ddd; padding:10px 20px;">
                    <p style="font-size:14px;margin:0 0 6px 0;"><span style="font-weight:bold;display:inline-block;min-width:150px">Order status</span><b style="color:green;font-weight:normal;margin:0">Success</b></p>
                    <p style="font-size:14px;margin:0 0 6px 0;"><span style="font-weight:bold;display:inline-block;min-width:146px">order ID</span> {{orderId}}</p>
                    <p style="font-size:14px;margin:0 0 6px 0;"><span style="font-weight:bold;display:inline-block;min-width:146px">product ID</span> {{productId}}</p>
                    <p style="font-size:14px;margin:0 0 0 0;"><span style="font-weight:bold;display:inline-block;min-width:146px">Order amount</span> Rs.{{amount}}</p>
                </td>
            </tr>
            <tr>

                <td>

                    <p style="margin-top:20px;margin-left: 20px; color:rgb(2, 75, 75);">
                        <b>

                            Process It As Fast As Possible to The Given address
                        </b>
                    </p>
                </td>
                <td style="height:35px;"></td>
            </tr>
            <tr>
                <td style="width:50%;padding:20px;vertical-align:top">
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px">Name</span> {{name}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">Email</span> {{mail}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">Phone</span>{{phone}}</p>

                </td>
                <td style="width:50%;padding:20px;vertical-align:top">
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">Address</span> {{address}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">City</span> {{city}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">State</span> {{state}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">Pincode</span> {{pincode}}</p>
                </td>
            </tr>

            <tr>
                <td colspan="2" style="padding:15px;">
                    <p style="font-size:14px;margin:0;padding:10px;border:solid 1px #ddd;font-weight:bold;">
                        <span style="display:block;font-size:13px;font-weight:normal;">{{headline}}</span> Rs. {{amount}}
                    </p>

                    <p>
                        <b>Product Description:-</b> {{description}}
                    </p>
                </td>
            </tr>
        </tbody>
        <tfooter>
            <tr>

                <td colspan="2" style="font-size:14px;padding:50px 15px 0 15px;">
                    <strong style="display:block;margin:0 0 10px 0;">Regards</strong> Zocaya<br>

                    <br>

                    <b>Email:</b> zocayamedia@gmail.com
                </td>
            </tr>
        </tfooter>
    </table>
</body>

</html>

paymentgateway/templates/orderInvoiceEmailTemplate_Customer.html
<html>

<body style="background-color:#e2e1e0;font-family: Open Sans, sans-serif;font-size:100%;font-weight:400;line-height:1.4;color:#000;">
    <table style="max-width:670px;margin:50px auto 10px;background-color:#fff;padding:50px;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;-webkit-box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);-moz-box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); border-top: solid 10px green;">
        <thead>
            <tr>
                <th style="text-align:left;font-weight:400;">

                    <h>New Purchase </h>

                </th>
                <th style="text-align:right;font-weight:400;">{{date}}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="height:35px;"></td>
            </tr>
            <tr>
                <td colspan="2" style="border: solid 1px #ddd; padding:10px 20px;">
                    <p style="font-size:14px;margin:0 0 6px 0;"><span style="font-weight:bold;display:inline-block;min-width:150px">Order status</span><b style="color:green;font-weight:normal;margin:0">Success</b></p>
                    <p style="font-size:14px;margin:0 0 6px 0;"><span style="font-weight:bold;display:inline-block;min-width:146px">order ID</span> {{orderId}}</p>
                    <p style="font-size:14px;margin:0 0 6px 0;"><span style="font-weight:bold;display:inline-block;min-width:146px">product ID</span> {{productId}}</p>
                    <p style="font-size:14px;margin:0 0 0 0;"><span style="font-weight:bold;display:inline-block;min-width:146px">Order amount</span> Rs.{{amount}}</p>
                </td>
            </tr>
            <tr>

                <td>

                    <p style="margin-top:20px;margin-left: 20px; color:rgb(2, 75, 75);">
                        <b>

                            Contact Seller Directly 
                        </b>
                    </p>
                </td>
                <td style="height:35px;"></td>
            </tr>
            <tr>
                <td style="width:50%;padding:20px;vertical-align:top">
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px">Name</span> {{name}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">Email</span> {{mail}}</p>
                    <p style="margin:0 0 10px 0;padding:0;font-size:14px;"><span style="display:block;font-weight:bold;font-size:13px;">Phone</span>{{phone}}</p>

                </td>

            </tr>

            <tr>
                <td colspan="2" style="padding:15px;">
                    <p style="font-size:14px;margin:0;padding:10px;border:solid 1px #ddd;font-weight:bold;">
                        <span style="display:block;font-size:13px;font-weight:normal;">{{headline}}</span> Rs. {{amount}}
                    </p>

                    <p>
                        <b>Product Description:-</b> {{description}}
                    </p>
                </td>
            </tr>
        </tbody>
        <tfooter>
            <tr>

                <td colspan="2" style="font-size:14px;padding:50px 15px 0 15px;">
                    <strong style="display:block;margin:0 0 10px 0;">Regards</strong> Zocaya<br>

                    <br>

                    <b>Email:</b> zocayamedia@gmail.com
                </td>
            </tr>
        </tfooter>
    </table>
</body>

</html>

paymentgateway/templates/redeemTemplateAkshat.html
<html>

<head>

    <style>
        * {
            box-sizing: border-box;
        }
        
        @import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap");
        body {
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: "Inter", sans-serif;
            background-color: #ededed;
            margin: 0;
        }
        
        .receipt {
            background-color: #fff;
            width: 22rem;
            position: relative;
            padding: 1rem;
            box-shadow: 0 -0.4rem 1rem -0.4rem rgba(0, 0, 0, 0.2);
        }
        
        .receipt:after {
            background-image: linear-gradient(135deg, #fff 0.5rem, transparent 0), linear-gradient(-135deg, #fff 0.5rem, transparent 0);
            background-position: left-bottom;
            background-repeat: repeat-x;
            background-size: 1rem;
            content: '';
            display: block;
            position: absolute;
            bottom: -1rem;
            left: 0;
            width: 100%;
            height: 1rem;
        }
        
        .receipt__header {
            text-align: center;
        }
        
        .receipt__title {
            color: #00c8eb;
            font-size: 1.6rem;
            font-weight: 700;
            margin: 1rem 0 0.5rem;
        }
        
        .receipt__date {
            font-size: 0.8rem;
            color: #666;
            margin: 0.5rem 0 1rem;
        }
        
        .receipt__list {
            margin: 2rem 0 1rem;
            padding: 0 1rem;
        }
        
        .receipt__list-row {
            display: flex;
            justify-content: space-between;
            margin: 1rem 0;
            position: relative;
        }
        
        .receipt__list-row:after {
            content: '';
            display: block;
            border-bottom: 1px dotted rgba(0, 0, 0, 0.15);
            width: 100%;
            height: 100%;
            position: absolute;
            top: -0.25rem;
            z-index: 1
        }
        
        .receipt__item {
            background-color: #fff;
            z-index: 2;
            padding: 0 0.15rem 0 0;
            color: #1f1f1f;
        }
        
        .receipt__cost {
            margin: 0;
            padding: 0 0 0 0.15rem;
            background-color: #fff;
            z-index: 2;
            color: #1f1f1f;
        }
        
        .receipt__list-row--total {
            border-top: 1px solid #FF619B;
            padding: 1.5rem 0 0;
            margin: 1.5rem 0 0;
            font-weight: 700;
        }
    </style>
</head>

<body>

    <div class="receipt">
        <header class="receipt__header">
            <p class="receipt__title">
                Bank Account Detail
            </p>
            <p class="receipt__date">{{date}}</p>
        </header>
        <dl class="receipt__list">
            <div class="receipt__list-row">
                <dt class="receipt__item">Zocaya Username</dt>
                <dd class="receipt__cost">{{username}}</dd>
            </div>
            <div class="receipt__list-row">
                <dt class="receipt__item">Email</dt>
                <dd class="receipt__cost">{{email}}</dd>
            </div>
            <div class="receipt__list-row">
                <dt class="receipt__item">Phone No</dt>
                <dd class="receipt__cost">{{phone}}</dd>
            </div>
            <div class="receipt__list-row">
                <dt class="receipt__item"></dt>
                <dd class="receipt__cost">{{accountnumber}}</dd>
            </div>
            <div class="receipt__list-row">
                <dt class="receipt__item">Account Holder Name</dt>
                <dd class="receipt__cost">{{accountholdername}}</dd>
            </div>
            <div class="receipt__list-row">
                <dt class="receipt__item">IFSC Code</dt>
                <dd class="receipt__cost">{{ifsccode}}</dd>
            </div>

            <div class="receipt__list-row receipt__list-row--total">
                <dt class="receipt__item">Total Amount Redeemed</dt>
                <dd class="receipt__cost">{{amount}}</dd>
            </div>
        </dl>
    </div>
</body>

</html>